FROM python:3.8-slim

RUN apt-get update && apt-get install -y \
    libopencv-dev \
    python3-opencv

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV FLASK_APP=run_me.py

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
